"""Delivering alert firings. A rule lists its channels; each firing records per-channel status.

    in_app    the alert_firings row itself IS the in-app feed (GET /v1/alerts/firings). Always on.
    webhook   POST JSON to the rule's URL, signed:
                  X-OpenGrid-Timestamp: <unix seconds>
                  X-OpenGrid-Signature: v1=<hex HMAC-SHA256(secret, "<timestamp>.<raw body>")>
              The per-rule secret is generated by OpenGrid, shown once when the rule is created,
              and stored Fernet-encrypted. Receivers should recompute the HMAC over the raw body,
              compare in constant time, and reject timestamps older than ~5 minutes (replay).
              URLs must be https and must not resolve to private / loopback / link-local
              addresses (SSRF), unless settings.alerts_webhook_allow_private (dev only).
              One attempt, 5 s timeout; failures are recorded, not retried (yet).
    email     INTERFACE ONLY: not implemented. A rule may list it; delivery records
              "not_implemented" so nobody believes an email was sent.
"""

from __future__ import annotations

import hashlib
import hmac
import ipaddress
import json
import secrets
import socket
import time
from urllib.parse import urlparse

import httpx

from config import settings

CHANNELS = ("in_app", "webhook", "email")


def new_secret() -> str:
    return "whsec_" + secrets.token_urlsafe(32)


def sign(secret: str, timestamp: int, body: bytes) -> str:
    mac = hmac.new(secret.encode(), str(timestamp).encode() + b"." + body, hashlib.sha256).hexdigest()
    return f"v1={mac}"


def verify_signature(secret: str, timestamp: int, body: bytes, header: str, tolerance_s: int = 300,
                     now: float | None = None) -> bool:
    """What a receiver does. Provided for tests and for documentation by example."""
    if abs((now or time.time()) - int(timestamp)) > tolerance_s:
        return False
    return hmac.compare_digest(sign(secret, int(timestamp), body), header)


def check_url(url: str) -> str:
    u = urlparse(url or "")
    if u.scheme not in ("https", "http") or not u.hostname:
        raise ValueError("webhook url must be an absolute https URL")
    if settings.alerts_webhook_allow_private:
        return url
    if u.scheme != "https":
        raise ValueError("webhook url must be https")
    try:
        infos = socket.getaddrinfo(u.hostname, u.port or 443, proto=socket.IPPROTO_TCP)
    except socket.gaierror:
        raise ValueError("webhook host does not resolve")
    for info in infos:
        ip = ipaddress.ip_address(info[4][0])
        if ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved or ip.is_multicast or ip.is_unspecified:
            raise ValueError("webhook url resolves to a private address")
    return url


def validate_channels(channels) -> list[dict]:
    out = [{"type": "in_app"}]
    for c in channels or []:
        if not isinstance(c, dict) or c.get("type") not in CHANNELS:
            raise ValueError(f"channel type must be one of {CHANNELS}")
        if c["type"] == "webhook":
            out.append({"type": "webhook", "url": check_url(c.get("url"))})
        elif c["type"] == "email":
            out.append({"type": "email", "to": c.get("to")})
    return out


# Tests swap this for an httpx.Client with a MockTransport.
def http_client() -> httpx.Client:
    return httpx.Client(timeout=5.0, follow_redirects=False)


def deliver(channels: list[dict], payload: dict, secret: str | None) -> tuple[list[str], dict]:
    """Returns (delivered_via, delivery_status)."""
    via, status = ["in_app"], {"in_app": "ok"}
    body = json.dumps(payload, default=str, separators=(",", ":")).encode()
    for c in channels:
        if c.get("type") == "webhook":
            if not secret:
                status["webhook"] = "error: no signing secret"
                continue
            ts = int(time.time())
            try:
                check_url(c["url"])
                with http_client() as client:
                    r = client.post(c["url"], content=body, headers={
                        "Content-Type": "application/json", "User-Agent": "OpenGrid-Alerts/1",
                        "X-OpenGrid-Timestamp": str(ts), "X-OpenGrid-Signature": sign(secret, ts, body)})
                status["webhook"] = "ok" if r.status_code < 300 else f"http {r.status_code}"
                if r.status_code < 300:
                    via.append("webhook")
            except Exception as e:
                status["webhook"] = f"error: {type(e).__name__}"
        elif c.get("type") == "email":
            status["email"] = "not_implemented"
    return via, status
