"""Delivering alert firings. A rule lists its channels; each firing records per-channel status.

    in_app    the alert_firings row itself IS the in-app feed (GET /v1/alerts/firings). Always on.
    webhook   POST JSON to the rule's URL, signed:
                  X-OpenGrid-Timestamp: <unix seconds>
                  X-OpenGrid-Signature: v1=<hex HMAC-SHA256(secret, "<timestamp>.<raw body>")>
              The per-rule secret is generated by OpenGrid, shown once when the rule is created,
              and stored Fernet-encrypted. Receivers should recompute the HMAC over the raw body,
              compare in constant time, and reject timestamps older than ~5 minutes (replay).
              SSRF: URLs must be https. At EVERY delivery the host is resolved once, every
              resolved address must be public (not private, loopback, link-local, CGNAT
              100.64/10, multicast, reserved, unspecified, IPv6 ULA / link-local, or an
              IPv4-mapped / 6to4 / Teredo wrapper of one), and the connection goes to that
              validated IP (Host header and TLS SNI/certificate check stay the hostname), so a
              DNS answer that changes between check and connect (rebinding) cannot redirect it.
              No redirects, 3 s connect / 5 s total, the response body is never read or stored.
              Tenants see only "ok" or "delivery_failed": no status codes or error types, so
              the webhook is not a port / host scanner. Details go to the server log.
              settings.alerts_webhook_allow_private (dev only) skips the address checks.
              One attempt; failures are recorded, not retried (yet).
    email     INTERFACE ONLY: not implemented. A rule may list it; delivery records
              "not_implemented" so nobody believes an email was sent.
"""

from __future__ import annotations

import hashlib
import hmac
import ipaddress
import json
import logging
import secrets
import socket
import time
from urllib.parse import urlparse

import httpx

from config import settings

log = logging.getLogger(__name__)
CHANNELS = ("in_app", "webhook", "email")
DELIVERY_FAILED = "delivery_failed"


def new_secret() -> str:
    return "whsec_" + secrets.token_urlsafe(32)


def sign(secret: str, timestamp: int, body: bytes) -> str:
    mac = hmac.new(secret.encode(), str(timestamp).encode() + b"." + body, hashlib.sha256).hexdigest()
    return f"v1={mac}"


def verify_signature(secret: str, timestamp: int, body: bytes, header: str, tolerance_s: int = 300,
                     now: float | None = None) -> bool:
    """What a receiver does. Provided for tests and for documentation by example."""
    if abs((now or time.time()) - int(timestamp)) > tolerance_s:
        return False
    return hmac.compare_digest(sign(secret, int(timestamp), body), header)


def blocked_ip(ip) -> bool:
    """True for anything that is not a plain public unicast address. Wrapped IPv4 inside IPv6
    (::ffff:a.b.c.d, 6to4 2002::/16, Teredo) is unwrapped and judged as IPv4."""
    if isinstance(ip, str):
        ip = ipaddress.ip_address(ip)
    if isinstance(ip, ipaddress.IPv6Address):
        inner = ip.ipv4_mapped or ip.sixtofour or (ip.teredo[1] if ip.teredo else None)
        if inner is not None:
            return True if ip.teredo else blocked_ip(inner)
        if ip in ipaddress.IPv6Network("64:ff9b::/96") or ip in ipaddress.IPv6Network("64:ff9b:1::/48"):
            return True  # NAT64: could reach any IPv4 behind the translator
    return (not ip.is_global or ip.is_private or ip.is_loopback or ip.is_link_local or ip.is_reserved
            or ip.is_multicast or ip.is_unspecified
            or (isinstance(ip, ipaddress.IPv4Address) and ip in ipaddress.IPv4Network("100.64.0.0/10")))


# Tests replace this to simulate DNS answers (including rebinding).
def getaddrinfo(host: str, port: int):
    return socket.getaddrinfo(host, port, proto=socket.IPPROTO_TCP)


def resolve_public(host: str, port: int) -> list[str]:
    """Resolve once; every address must be public, else ValueError. Returns the addresses."""
    try:
        literal = ipaddress.ip_address(host.strip("[]"))
    except ValueError:
        literal = None
    if literal is not None:
        addrs = [str(literal)]
    else:
        try:
            addrs = sorted({info[4][0] for info in getaddrinfo(host, port)})
        except (socket.gaierror, UnicodeError, OSError):
            raise ValueError("webhook host does not resolve")
    if not addrs:
        raise ValueError("webhook host does not resolve")
    for a in addrs:
        if blocked_ip(a.split("%", 1)[0]):
            raise ValueError("webhook url must resolve only to public addresses")
    return addrs


def check_url(url: str) -> str:
    u = urlparse(url or "")
    if u.scheme not in ("https", "http") or not u.hostname:
        raise ValueError("webhook url must be an absolute https URL")
    if u.username or u.password:
        raise ValueError("webhook url must not contain credentials")
    if settings.alerts_webhook_allow_private:
        return url
    if u.scheme != "https":
        raise ValueError("webhook url must be https")
    resolve_public(u.hostname, u.port or 443)
    return url


def pinned_request(url: str) -> tuple[str, dict, dict]:
    """(url with the host replaced by a validated IP, extra headers, request extensions).
    The Host header and TLS SNI (which httpcore also uses for certificate hostname checks) stay the
    original hostname, so TLS still proves we reached the named host, but the TCP connection can only
    go to the address we validated."""
    u = urlparse(url)
    port = u.port or (443 if u.scheme == "https" else 80)
    ip = resolve_public(u.hostname, port)[0]
    host_in_url = f"[{ip}]" if ":" in ip else ip
    netloc = host_in_url + (f":{u.port}" if u.port else "")
    pinned = u._replace(netloc=netloc).geturl()
    host_header = u.hostname + (f":{u.port}" if u.port else "")
    return pinned, {"Host": host_header}, {"sni_hostname": u.hostname}


def validate_channels(channels) -> list[dict]:
    out = [{"type": "in_app"}]
    for c in channels or []:
        if not isinstance(c, dict) or c.get("type") not in CHANNELS:
            raise ValueError(f"channel type must be one of {CHANNELS}")
        if c["type"] == "webhook":
            out.append({"type": "webhook", "url": check_url(c.get("url"))})
        elif c["type"] == "email":
            out.append({"type": "email", "to": c.get("to")})
    return out


# Tests swap this for an httpx.Client with a MockTransport.
def http_client() -> httpx.Client:
    return httpx.Client(timeout=httpx.Timeout(5.0, connect=3.0), follow_redirects=False, trust_env=False)


def deliver(channels: list[dict], payload: dict, secret: str | None) -> tuple[list[str], dict]:
    """Returns (delivered_via, delivery_status)."""
    via, status = ["in_app"], {"in_app": "ok"}
    body = json.dumps(payload, default=str, separators=(",", ":")).encode()
    for c in channels:
        if c.get("type") == "webhook":
            if not secret:
                status["webhook"] = DELIVERY_FAILED
                log.warning("webhook channel without a signing secret")
                continue
            ts = int(time.time())
            headers = {"Content-Type": "application/json", "User-Agent": "OpenGrid-Alerts/1",
                       "X-OpenGrid-Timestamp": str(ts), "X-OpenGrid-Signature": sign(secret, ts, body)}
            try:
                if settings.alerts_webhook_allow_private:  # dev only: no pinning, plain hostname
                    check_url(c["url"])
                    url, extra, ext = c["url"], {}, {}
                else:
                    # ONE resolution: validated and pinned together (no second lookup to rebind)
                    u = urlparse(c["url"] or "")
                    if u.scheme != "https" or not u.hostname or u.username or u.password:
                        raise ValueError("webhook url must be an absolute https URL")
                    url, extra, ext = pinned_request(c["url"])
                with http_client() as client:
                    # stream(): the response body is never read, so nothing of it is stored or echoed
                    with client.stream("POST", url, content=body, headers={**headers, **extra},
                                       extensions=ext) as r:
                        code = r.status_code
                ok = 200 <= code < 300
                status["webhook"] = "ok" if ok else DELIVERY_FAILED
                if ok:
                    via.append("webhook")
                else:
                    log.info("webhook delivery got HTTP %s", code)
            except Exception as e:  # noqa: BLE001 - every failure looks the same to the tenant
                log.info("webhook delivery failed: %s", type(e).__name__)
                status["webhook"] = DELIVERY_FAILED
        elif c.get("type") == "email":
            status["email"] = "not_implemented"
    return via, status
