"""initial schema

Revision ID: 337d80df1c26
Revises: 
Create Date: 2026-09-21 00:12:04.788606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '337d80df1c26'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_listings',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('listing_id', sa.String(length=256), nullable=False),
    sa.Column('sku', sa.String(length=256), nullable=False),
    sa.Column('raw_gpu_name', sa.String(length=160), nullable=False),
    sa.Column('canonical_gpu_name', sa.String(length=160), nullable=True),
    sa.Column('gpu_count', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('price_per_gpu_hour', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('price_per_instance_hour', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('market_type', sa.String(length=24), nullable=True),
    sa.Column('provider_tier', sa.String(length=24), nullable=True),
    sa.Column('interruptible', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=16), nullable=True),
    sa.Column('vcpu', sa.Integer(), nullable=True),
    sa.Column('ram_gb', sa.Float(), nullable=True),
    sa.Column('storage_gb', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'listing_id')
    )
    op.create_index('ix_listing_available', 'compute_listings', ['available'], unique=False)
    op.create_index('ix_listing_canonical', 'compute_listings', ['canonical_gpu_name'], unique=False)
    op.create_table('raw_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_raw_provider_endpoint_time', 'raw_snapshots', ['provider', 'endpoint', 'fetched_at'], unique=False)
    op.create_table('reference_prices',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('original_value', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('discount_applied', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_listed', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider', 'name')
    )
    op.create_index('ix_refprice_provider', 'reference_prices', ['provider'], unique=False)
    op.create_table('listing_observations',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('listing_id', sa.String(length=256), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price_per_gpu_hour', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('price_per_instance_hour', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('capacity_unit', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['provider', 'listing_id'], ['compute_listings.provider', 'compute_listings.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider', 'listing_id', 'observed_at')
    )
    op.create_index('ix_obs_listing_time', 'listing_observations', ['provider', 'listing_id', 'observed_at'], unique=False)
    op.create_index('ix_obs_time', 'listing_observations', ['observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_obs_time', table_name='listing_observations')
    op.drop_index('ix_obs_listing_time', table_name='listing_observations')
    op.drop_table('listing_observations')
    op.drop_index('ix_refprice_provider', table_name='reference_prices')
    op.drop_table('reference_prices')
    op.drop_index('ix_raw_provider_endpoint_time', table_name='raw_snapshots')
    op.drop_table('raw_snapshots')
    op.drop_index('ix_listing_canonical', table_name='compute_listings')
    op.drop_index('ix_listing_available', table_name='compute_listings')
    op.drop_table('compute_listings')
    # ### end Alembic commands ###
